-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(PRODUCT.PRICE*OFFLINE_SALE.SALES_AMOUNT) as SALES
FROM PRODUCT
JOIN OFFLINE_SALE ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY SUM(PRODUCT.PRICE*OFFLINE_SALE.SALES_AMOUNT) DESC , PRODUCT.PRODUCT_CODE ASC;