-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",FILE.BOARD_ID,"/",FILE.FILE_ID,FILE.FILE_NAME,FILE.FILE_EXT) as FILE_PATH
from USED_GOODS_FILE as FILE 
inner join USED_GOODS_BOARD as BOARD
on FILE.BOARD_ID = BOARD.BOARD_ID
where BOARD.VIEWS = (select max(FILE.VIEWS) from USED_GOODS_BOARD as FILE)
order by FILE.FILE_ID desc